var t, menor;
calc = document.getElementById("calc");
n1 = document.getElementById("num1");
n2 = document.getElementById("num2");
n3 = document.getElementById("num3");

if (n1 < n2) {
	t = n1;
}else{
	t = n2;
	}
	if (t < n3) {
		menor = t;
		}else{
			menor = n3;
			}
			alert("El menor es" + menor);
			

			
			
function CentrimetosPulg(a, b){
	
	}

var numero1= document.getElementById("Introduce la altura: ");
calc = document.getElementById("calc");

	n1 = document.getElementById(numero1);
	

	calc = n1 * 0.393701;
	document.writeln("<br> El resultado es: " + calc);
	default: alert ("Numero de operacion invalido....")
	break;
	function Millas(a, b){
	return a*b;
	}


var numero1= prompt("Introduce las millas a calcular: ");
	

	n1 = parseInt(numero1);
	n2 = parseInt(1.60934);

	r = n1 * 1.60934;
	document.writeln("<br> El resultado es: " + r);